name = "Comonicon"
uuid = "863f3e99-da2a-4334-8734-de3dacbe5542"
authors = ["Roger-luo and contributors"]
version = "0.10.2"

[deps]
ComoniconBuilder = "0acea522-3a8c-4b93-9211-1fc67cbf95d9"
ComoniconOptions = "a25bc8ac-9d24-42b2-8edd-3d267ec19fc5"
ComoniconTargetExpr = "d6dfd36b-42f3-4a9f-a1cb-6f1a052fed42"
ComoniconTypes = "d0eb39ce-029e-40d1-add6-e32b3165f6a3"
ComoniconZSHCompletion = "dcf03e4a-d036-4ede-96c9-024e9e9eed12"
Configurations = "5218b696-f38b-4ac9-8b61-a12ec717816d"
ExproniconLite = "55351af7-c7e9-48d6-89ff-24e801d99491"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
ComoniconBuilder = "0.1"
ComoniconOptions = "0.1"
ComoniconTargetExpr = "0.1"
ComoniconTypes = "0.1"
ComoniconZSHCompletion = "0.1"
Configurations = "0.15"
ExproniconLite = "0.6"
julia = "1.6"
