name = "Comonicon"
uuid = "863f3e99-da2a-4334-8734-de3dacbe5542"
authors = ["Roger-luo and contributors"]
version = "0.5.6"

[deps]
CRC32c = "8bf52ea8-c179-5cab-976a-9e18b702a9bc"
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MatchCore = "5dd3f0b1-72a9-48ad-ae6e-79f673da005f"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
ExprTools = "0.1"
MatchCore = "0.1"
PackageCompiler = "1.2"
julia = "1"
