name = "Comonicon"
uuid = "863f3e99-da2a-4334-8734-de3dacbe5542"
authors = ["Roger-luo and contributors"]
version = "0.12.17"

[deps]
Configurations = "5218b696-f38b-4ac9-8b61-a12ec717816d"
ExproniconLite = "55351af7-c7e9-48d6-89ff-24e801d99491"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
Configurations = "0.17"
ExproniconLite = "0.6"
PackageCompiler = "2"
Scratch = "1"
TOML = "1"
julia = "1.6"
