name = "Comonicon"
uuid = "863f3e99-da2a-4334-8734-de3dacbe5542"
authors = ["Roger-luo and contributors"]
version = "0.2.5"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
MatchCore = "5dd3f0b1-72a9-48ad-ae6e-79f673da005f"
CRC32c = "8bf52ea8-c179-5cab-976a-9e18b702a9bc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"

[compat]
julia = "1"
PackageCompiler = "1.2"
MatchCore = "0.1"
ExprTools = "0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
