[deps]
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"
DocThemeIndigo = "8bac0ac5-51bf-41f9-885e-2bf1ac2bec5f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[sources]
Comonicon = { path = ".." }

[compat]
DocThemeIndigo = "0.1"
Documenter = "1"
